### ISSUE TITLE
Relying on indirect includes is not portable

### ISSUE THREAD

**Issue by musicinmybrain** [rafalcieslak/harmonySEQ#7]
Quite a few files use standard library functionality without including the corresponding headers. For example `src/Engine.hpp` uses `std::atomic<bool>` but does not `#include <atomic>`. Presumably this works on the author’s system, as the needed headers happen to be included indirectly.

However, as I’m updating the Fedora package to 0.17, I’m finding I have quite a few build failures related to missing includes. In general, the safe approach is to include what you use in each file where you use it.

Would you, in principle, accept a PR that added direct includes to every source file (at least for things in library namespaces like `std::` or `boost::`)?

**Comment by rafalcieslak** [comment]
To avoid cross-contamination from my personal OS installation, I normally test builds in a fresh Docker container based on a distro's image, though until now I did not include Fedora on my list of distros being used in this test. Looking at this now, builds on Debian work fine, but I am able to reproduce your issues with a Fedora 33 image. Now, my C++ skills are bit rusty at this point, but I'm surprised to learn that transitive includes are not deterministic... though it does make sense when third party libraries incorporated change their header contents in a newer release.

I've spend the weekend trying to get `iwyu` to work, and while I'm happy with its results (as they look valid and very helpful), in my testing they make the situation on Fedora even worse, with many new compilation issues that can no longer be easily explained. I will likely take me a longer while to examine `iwyu`'s full output and understand all the details. So until I get this done, I'm happy to accept even a band-aid PR that helps in your specific scenario.

**Comment by musicinmybrain** [comment]
> I'm surprised to learn that transitive includes are not deterministic…

What’s happening here is something like (a contrived example)

```cpp
#include <deque>

int returnThree() {
    std::vector<int> x(3);
    return x.size();
}
```

…and it works, because (let’s say) the implementation of `std::deque` happens to use `std::vector` internally, so `#include <deque>` ends up getting you `#include <vector>`. It’s deterministic in the sense that it will always work with the same compiler settings and standard library.

But maybe you turn on support for a later C++ version and it toggles some `#ifdef`, or you use a different C++ standard library version, or another platform or compiler uses a different standard library implementation altogether, and now the implementation of `std::deque` no longer uses `std::vector` and you have a compile error.

Or, as you pointed out, you could have been getting the include through a third-party library like gtkmm or Boost, and they can change their implementations as well.

-----

There are a few cases where transitive includes are specified in the standard, like that `#include <iostream>` gets you `#include <ios>`, and you can rely on these, although I guess there is still no harm in including each header directly.

Now, things like including `<vector>` in your own `foo.hpp` and then using `std::vector` in `bar.cpp` without explicitly including `<vector>` because `bar.cpp` has `#include foo.hpp`—well, that will always work, but it’s easy to break with any refactoring, and including the same header twice has almost no cost due to use of include guards or `#pragma once`, so my *personal* preference is to directly include everything that every file needs, because I think doing this as a consistent habit makes it harder to miss the transitive includes that *are* unreliable. Somebody could validly decide they didn’t like doing things this way, though.

-----

I’m happy to offer a manually-constructed PR that adds standard-library includes where they are used. Since you only use a couple dozen standard library functions and classes, and you are consistent with how you handle namespaces, it’s easy enough to do this with simple grepping.

I am curious how the results compare with `iwyu`; I’ve heard of it but not tested it. I know Google warns it’s “alpha-quality,” but I know it’s still been useful for some people.

**Comment by rafalcieslak** [comment]
Your logic is sound :+1: I'm disappointed that different std lib implementations and variants tend to transitively include other unrelated headers, but it is what it is.

I think the reason `iwyu` isn't useful for this scenario is because it doesn't follow the specification / the standard and instead empirically looks inside the specific header files as available in the system it runs on. It thus optimizes and corrects header inclusions for that particular version of standard and auxiliary libraries. So while it improves consistency on a specific build setup, it does not make the code any more portable... Most likely manually adding relevant headers is going to be more effective.

I could selectively apply `iwyu`'s recommendations, only adding new headers and not removing those it thinks are redundant, which should only improve things (maybe at the price of inelegant lists of included headers in some files), but again, the result will only be guaranteed to work on the specific system and libs as available on one system 🤔
